// server/src/models/dummyData.ts
import { Product } from '../types/Product';

export const products: Product[] = [
  {
    id: '1',
    name: 'Wireless Bluetooth Headphones',
    description: 'High-quality sound with noise-cancelling features and comfortable earcups.',
    price: 99.99,
    imageUrl: 'https://via.placeholder.com/300x300?text=Headphones',
    category: 'Electronics',
    rating: 4.5,
    numReviews: 120,
    countInStock: 50,
  },
  {
    id: '2',
    name: 'Ergonomic Office Chair',
    description: 'Adjustable chair with lumbar support for long hours of comfortable work.',
    price: 249.00,
    imageUrl: 'https://via.placeholder.com/300x300?text=OfficeChair',
    category: 'Furniture',
    rating: 4.8,
    numReviews: 85,
    countInStock: 20,
  },
  {
    id: '3',
    name: 'Smartwatch Series 7',
    description: 'Track your fitness, receive notifications, and make calls from your wrist.',
    price: 329.99,
    imageUrl: 'https://via.placeholder.com/300x300?text=Smartwatch',
    category: 'Electronics',
    rating: 4.2,
    numReviews: 210,
    countInStock: 30,
  },
  {
    id: '4',
    name: 'Portable Coffee Maker',
    description: 'Compact and easy-to-use coffee maker for brewing on the go.',
    price: 45.50,
    imageUrl: 'https://via.placeholder.com/300x300?text=CoffeeMaker',
    category: 'Home Appliances',
    rating: 4.0,
    numReviews: 50,
    countInStock: 100,
  },
  {
    id: '5',
    name: 'Gaming Laptop RTX 3080',
    description: 'Powerful gaming laptop with latest generation GPU and high refresh rate display.',
    price: 1899.00,
    imageUrl: 'https://via.placeholder.com/300x300?text=GamingLaptop',
    category: 'Electronics',
    rating: 4.7,
    numReviews: 95,
    countInStock: 15,
  },
  {
    id: '6',
    name: 'Organic Cotton T-Shirt',
    description: 'Soft and breathable 100% organic cotton t-shirt in various colors.',
    price: 25.00,
    imageUrl: 'https://via.placeholder.com/300x300?text=Tshirt',
    category: 'Apparel',
    rating: 4.3,
    numReviews: 60,
    countInStock: 200,
  },
];